using AzCliManagedIdentity.Framework;
using Serilog;

namespace AzCliManagedIdentity.ManagedIdentity;

public static class SetupAzureCliFiles
{
    /// <summary>
    /// Copy all required Azure CLI config files to default Azure CLI config directory on container startup.
    /// </summary>
    /// <remarks>
    /// The AzureCli@2 task in Azure Pipelines clears credential files after the task completes.
    /// Therefore, we copy the mounted files to a container-specific directory (i.e. ~/.azure) on container startup.
    /// For each request, we create a temp directory, and merge files from both the mounted volume and the container-specific directory.
    /// Hence, if the credentials are cleared, the container-specific directory will still have the files required to get a token.
    /// However, during development where the mounted volume isn't cleared (in fact contents may change), we get any new files from the mounted volume for each request.
    /// </remarks>
    public static void CopyFilesOnStartup()
    {
        // Copy files from the source Azure CLI config directory (i.e. mounted volume)
        var sourceDir = GetSourceConfigDir();
        var cliDir = GetCliConfigDir();
        Log.Information("Source directory {Directory}", sourceDir);
        Log.Information("CLI directory {Directory}", cliDir);

        foreach (var file in GetFiles(sourceDir, SourceFilesToCopy))
            CopyFile(file, cliDir);
    }

    /// <summary>
    /// Copies the required Azure CLI config files to a temporary directory to be used for the Azure CLI token request.
    /// </summary>
    public static void CopyFilesForRequest(string tempDir)
    {
        // First: Copy files from the default Azure CLI config directory
        // These files may have been copied at container startup
        foreach (var file in GetFiles(GetCliConfigDir(), CliFilesToCopy))
            CopyFile(file, tempDir);
        foreach (var file in GetFiles(GetCliConfigDir(), SourceFilesToCopy))
            CopyFile(file, tempDir);

        // Then copy the files from the source Azure CLI config directory (i.e. mounted volume)
        // This will ensure we get any files that have changed since container startup
        foreach (var file in GetFiles(GetSourceConfigDir(), SourceFilesToCopy))
            CopyFile(file, tempDir);
    }

    /// <summary>
    /// Files generated by the Azure CLI itself (i.e. not credentials).
    /// </summary>
    private static readonly string[] CliFilesToCopy =
    [
        "versionCheck.json",
        "commandIndex.json"
    ];

    /// <summary>
    /// Wildcard file names to copy from the mounted Azure CLI config directory. These are the files required to get a token.
    /// </summary>
    private static readonly string[] SourceFilesToCopy =
    [
        "az.*",
        "azureProfile.json",
        "*config",
        "msal_http*",
        // Ignore msal_token*.bin and service_principal_entries.bin which are encrypted and therefore unreadable by the container
        "msal_token*.json",
        "service_principal_entries.json",
    ];

    private static IEnumerable<string> GetFiles(string directory, string[] patterns) =>
        patterns.SelectMany(pattern => Directory.GetFiles(directory, pattern, SearchOption.TopDirectoryOnly));

    /// <summary>
    /// Returns default Azure CLI config directory (i.e. ~/.azure on Linux or %USERPROFILE%\.azure on Windows).
    /// </summary>
    /// <remarks>
    /// We use this directory to store config files at container startup.
    /// </remarks>
    private static string GetCliConfigDir()
    {
        var homeEnvVar = OperatingSystem.IsWindows() ? "USERPROFILE" : "HOME";
        var homeDir = EnvVariableHelpers.GetValue(homeEnvVar);
        return Path.Combine(homeDir, ".azure");
    }

    /// <summary>
    /// Gets the source Azure CLI config (i.e. mounted volume) directory.
    /// </summary>
    /// <remarks>
    /// This directory is expected to be mounted as a read-only volume in the container.
    /// </remarks>
    public static string GetSourceConfigDir()
    {
        // Then copy the files from the source Azure CLI config directory (i.e. mounted volume)
        var directory = EnvVariableHelpers.GetValue("SOURCE_AZURE_CONFIG");
        if (!Directory.Exists(directory))
            throw new DirectoryNotFoundException($"Source Azure CLI config directory not found: '{directory}'");
        return directory;
    }
    
    private static void CopyFile(string source, string destination)
    {
        var destFile = Path.Combine(destination, Path.GetFileName(source));
        File.Copy(source, destFile, true);
    }
}